-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.campaign_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  campaign_name text NOT NULL DEFAULT 'Untitled Campaign'::text,
  website_url text,
  website_analysis jsonb,
  offering_description text,
  pain_points jsonb DEFAULT '[]'::jsonb,
  proof_points jsonb DEFAULT '[]'::jsonb,
  coaching_points jsonb DEFAULT '[]'::jsonb,
  email_body_coaching jsonb DEFAULT '[]'::jsonb,
  filters jsonb DEFAULT '{}'::jsonb,
  selected_leads jsonb DEFAULT '[]'::jsonb,
  current_step text DEFAULT 'targeting'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT campaign_drafts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  description text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'completed'::text])),
  sequence_template text DEFAULT 'email_first'::text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT campaigns_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.icp_filter_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  profile_name character varying NOT NULL,
  description text,
  filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  search_type character varying DEFAULT 'people'::character varying,
  usage_count integer DEFAULT 0,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT icp_filter_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT icp_filter_profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT icp_filter_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid,
  full_name text NOT NULL,
  first_name text,
  last_name text,
  email text,
  phone text,
  title text,
  headline text,
  seniority text,
  company text,
  industry text,
  location text,
  linkedin_url text,
  twitter_url text,
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'replied'::text, 'positive'::text, 'neutral'::text, 'negative'::text, 'unsubscribed'::text])),
  source text DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['manual'::text, 'zoominfo'::text, 'apollo'::text, 'clearbit'::text, 'website_visitor'::text, 'syndie'::text])),
  enrichment_data jsonb DEFAULT '{}'::jsonb,
  verified boolean DEFAULT false,
  confidence numeric DEFAULT 0,
  smartlead_campaign_id text,
  last_email_event text,
  last_event_timestamp timestamp with time zone,
  syndie_lead_id text UNIQUE,
  linkedin_connection_status text DEFAULT 'not_connected'::text CHECK (linkedin_connection_status = ANY (ARRAY['not_connected'::text, 'pending'::text, 'connected'::text, 'replied'::text, 'bounced'::text, 'not_interested'::text])),
  steps jsonb DEFAULT '[]'::jsonb CHECK (validate_syndie_steps(steps)),
  campaign_info jsonb DEFAULT '{}'::jsonb,
  seat_info jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT leads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.leads_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  list_name text NOT NULL,
  campaign_id uuid,
  organization_id uuid NOT NULL,
  s3_key text NOT NULL,
  s3_bucket text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  active integer NOT NULL DEFAULT 1,
  CONSTRAINT leads_files_pkey PRIMARY KEY (id),
  CONSTRAINT fk_campaign FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT fk_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  role character varying DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'member'::character varying, 'viewer'::character varying]::text[])),
  permissions jsonb DEFAULT '{}'::jsonb,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'pending'::character varying]::text[])),
  invited_by uuid,
  invited_at timestamp with time zone,
  joined_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_org_id text NOT NULL UNIQUE,
  name text NOT NULL,
  slug text UNIQUE,
  logo_url text,
  website_url text,
  industry text,
  company_size character varying,
  plan character varying DEFAULT 'free'::character varying CHECK (plan::text = ANY (ARRAY['free'::character varying, 'starter'::character varying, 'pro'::character varying, 'enterprise'::character varying]::text[])),
  billing_email text,
  subscription_status character varying DEFAULT 'active'::character varying,
  monthly_campaign_limit integer DEFAULT 5,
  monthly_lead_limit integer DEFAULT 1000,
  user_limit integer DEFAULT 5,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sequence_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  lead_id uuid,
  step_number integer NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['email'::text, 'linkedin_invite'::text, 'linkedin_message'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'scheduled'::text, 'sent'::text, 'failed'::text, 'skipped'::text])),
  send_time timestamp with time zone,
  sent_at timestamp with time zone,
  payload jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sequence_steps_pkey PRIMARY KEY (id),
  CONSTRAINT sequence_steps_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.user_profile (
  user_id uuid NOT NULL,
  company_name text,
  website_url text,
  site_summary text,
  icp jsonb DEFAULT '{}'::jsonb,
  linkedin_connected boolean DEFAULT false,
  completed boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  core_offer text,
  icp_summary text,
  target_personas jsonb,
  case_studies jsonb,
  lead_magnets jsonb,
  competitive_advantages ARRAY,
  technology_stack ARRAY,
  social_proof jsonb,
  website_analyzed_at timestamp with time zone,
  analysis_version integer DEFAULT 1,
  onboarding_completed boolean DEFAULT false,
  onboarding_step_completed jsonb DEFAULT '{}'::jsonb,
  linkedin_accounts_connected integer DEFAULT 0,
  organization_id uuid,
  CONSTRAINT user_profile_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_profile_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_id text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  full_name text,
  company_name text,
  website_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  isAdmin smallint DEFAULT '0'::smallint,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.website_analysis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  website_url text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'analyzing'::text, 'completed'::text, 'failed'::text])),
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  core_offer text,
  icp_summary text,
  target_personas jsonb DEFAULT '[]'::jsonb,
  case_studies jsonb DEFAULT '[]'::jsonb,
  lead_magnets jsonb DEFAULT '[]'::jsonb,
  competitive_advantages ARRAY DEFAULT '{}'::text[],
  technology_stack ARRAY DEFAULT '{}'::text[],
  social_proof jsonb DEFAULT '{}'::jsonb,
  pages_analyzed integer DEFAULT 0,
  total_pages_found integer DEFAULT 0,
  analysis_duration_seconds integer,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  analysis_status character varying DEFAULT 'pending'::character varying CHECK (analysis_status::text = ANY (ARRAY['pending'::character varying, 'analyzing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  industry character varying,
  business_model character varying,
  target_market_summary text,
  tech_stack jsonb DEFAULT '[]'::jsonb,
  pages_discovered jsonb DEFAULT '[]'::jsonb,
  ai_model_used character varying,
  confidence_score numeric,
  started_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT website_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT website_analysis_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT website_analysis_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);