-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.campaign_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  campaign_name text NOT NULL DEFAULT 'Untitled Campaign'::text,
  website_url text,
  website_analysis jsonb,
  offering_description text,
  pain_points jsonb DEFAULT '[]'::jsonb,
  proof_points jsonb DEFAULT '[]'::jsonb,
  coaching_points jsonb DEFAULT '[]'::jsonb,
  email_body_coaching jsonb DEFAULT '[]'::jsonb,
  filters jsonb DEFAULT '{}'::jsonb,
  selected_leads jsonb DEFAULT '[]'::jsonb,
  current_step text DEFAULT 'targeting'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT campaign_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_drafts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.campaign_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  lead_id uuid,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'completed'::text, 'opted_out'::text])),
  added_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT campaign_leads_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_leads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT campaign_leads_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT campaign_leads_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  description text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'completed'::text])),
  sequence_template text DEFAULT 'email_first'::text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT campaigns_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.integration_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['gmail'::text, 'outlook'::text, 'linkedin'::text, 'phantombuster'::text, 'zoominfo'::text, 'apollo'::text])),
  credentials jsonb NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT integration_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT integration_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT integration_credentials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  full_name text NOT NULL,
  email text,
  linkedin_url text,
  company text,
  title text,
  industry text,
  location text,
  phone text,
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'replied'::text, 'positive'::text, 'neutral'::text, 'negative'::text, 'unsubscribed'::text])),
  source text DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['manual'::text, 'zoominfo'::text, 'apollo'::text, 'clearbit'::text, 'website_visitor'::text])),
  enrichment_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT leads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.linkedin_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  linkedin_id character varying NOT NULL,
  access_token text NOT NULL,
  refresh_token text,
  token_expires_at timestamp with time zone,
  profile_data jsonb DEFAULT '{}'::jsonb,
  display_name character varying,
  profile_picture_url text,
  headline text,
  industry character varying,
  location character varying,
  is_active boolean DEFAULT true,
  last_used_at timestamp with time zone,
  usage_count integer DEFAULT 0,
  daily_message_count integer DEFAULT 0,
  daily_reset_date date DEFAULT CURRENT_DATE,
  is_rate_limited boolean DEFAULT false,
  rate_limit_reset_at timestamp with time zone,
  last_message_sent_at timestamp with time zone,
  connection_status character varying DEFAULT 'connected'::character varying,
  last_error text,
  health_check_at timestamp with time zone DEFAULT now(),
  connected_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT linkedin_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT linkedin_accounts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT linkedin_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lead_id uuid,
  campaign_id uuid,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['outbound'::text, 'inbound'::text])),
  channel text NOT NULL CHECK (channel = ANY (ARRAY['email'::text, 'linkedin'::text, 'phone'::text, 'other'::text])),
  subject text,
  body text,
  status text DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['sent'::text, 'delivered'::text, 'opened'::text, 'replied'::text, 'bounced'::text])),
  external_id text,
  meta jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT messages_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  role character varying DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'member'::character varying, 'viewer'::character varying]::text[])),
  permissions jsonb DEFAULT '{}'::jsonb,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'pending'::character varying]::text[])),
  invited_by uuid,
  invited_at timestamp with time zone,
  joined_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT organization_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_org_id text NOT NULL UNIQUE,
  name text NOT NULL,
  slug text UNIQUE,
  logo_url text,
  website_url text,
  industry text,
  company_size character varying,
  plan character varying DEFAULT 'free'::character varying CHECK (plan::text = ANY (ARRAY['free'::character varying, 'starter'::character varying, 'pro'::character varying, 'enterprise'::character varying]::text[])),
  billing_email text,
  subscription_status character varying DEFAULT 'active'::character varying,
  monthly_campaign_limit integer DEFAULT 5,
  monthly_lead_limit integer DEFAULT 1000,
  user_limit integer DEFAULT 5,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.page_analysis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  website_analysis_id uuid NOT NULL,
  url text NOT NULL,
  title text,
  content_summary text,
  key_insights jsonb DEFAULT '[]'::jsonb,
  page_type text,
  created_at timestamp with time zone DEFAULT now(),
  analyzed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT page_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT page_analysis_website_analysis_id_fkey FOREIGN KEY (website_analysis_id) REFERENCES public.website_analysis(id)
);
CREATE TABLE public.sequence_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  lead_id uuid,
  step_number integer NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['email'::text, 'linkedin_invite'::text, 'linkedin_message'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'scheduled'::text, 'sent'::text, 'failed'::text, 'skipped'::text])),
  send_time timestamp with time zone,
  sent_at timestamp with time zone,
  payload jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sequence_steps_pkey PRIMARY KEY (id),
  CONSTRAINT sequence_steps_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
  CONSTRAINT sequence_steps_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.user_profile (
  user_id uuid NOT NULL,
  company_name text,
  website_url text,
  site_summary text,
  icp jsonb DEFAULT '{}'::jsonb,
  linkedin_connected boolean DEFAULT false,
  completed boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  core_offer text,
  icp_summary text,
  target_personas jsonb,
  case_studies jsonb,
  lead_magnets jsonb,
  competitive_advantages ARRAY,
  technology_stack ARRAY,
  social_proof jsonb,
  website_analyzed_at timestamp with time zone,
  analysis_version integer DEFAULT 1,
  onboarding_completed boolean DEFAULT false,
  onboarding_step_completed jsonb DEFAULT '{}'::jsonb,
  linkedin_accounts_connected integer DEFAULT 0,
  organization_id uuid,
  CONSTRAINT user_profile_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_profile_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_id text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  full_name text,
  company_name text,
  website_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.website_analysis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  website_url text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'analyzing'::text, 'completed'::text, 'failed'::text])),
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  core_offer text,
  icp_summary text,
  target_personas jsonb DEFAULT '[]'::jsonb,
  case_studies jsonb DEFAULT '[]'::jsonb,
  lead_magnets jsonb DEFAULT '[]'::jsonb,
  competitive_advantages ARRAY DEFAULT '{}'::text[],
  technology_stack ARRAY DEFAULT '{}'::text[],
  social_proof jsonb DEFAULT '{}'::jsonb,
  pages_analyzed integer DEFAULT 0,
  total_pages_found integer DEFAULT 0,
  analysis_duration_seconds integer,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  analysis_status character varying DEFAULT 'pending'::character varying CHECK (analysis_status::text = ANY (ARRAY['pending'::character varying, 'analyzing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  industry character varying,
  business_model character varying,
  target_market_summary text,
  tech_stack jsonb DEFAULT '[]'::jsonb,
  pages_discovered jsonb DEFAULT '[]'::jsonb,
  ai_model_used character varying,
  confidence_score numeric,
  started_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT website_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT website_analysis_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT website_analysis_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);