-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.account_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  activity_type text NOT NULL CHECK (activity_type = ANY (ARRAY['test_message'::text, 'profile_visit'::text, 'connection_request'::text, 'message_sent'::text, 'comment_post'::text, 'like_post'::text, 'share_post'::text, 'follow_user'::text, 'unfollow_user'::text, 'campaign_start'::text, 'campaign_end'::text, 'webhook_notification'::text, 'sync_data'::text])),
  activity_data jsonb DEFAULT '{}'::jsonb,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  error_message text,
  external_id text,
  target_profile_id text,
  campaign_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT account_activities_pkey PRIMARY KEY (id),
  CONSTRAINT account_activities_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.user_accounts(id)
);
CREATE TABLE public.campaign_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  campaign_name text NOT NULL DEFAULT 'Untitled Campaign'::text,
  website_url text,
  website_analysis jsonb,
  offering_description text,
  pain_points jsonb DEFAULT '[]'::jsonb,
  proof_points jsonb DEFAULT '[]'::jsonb,
  coaching_points jsonb DEFAULT '[]'::jsonb,
  email_body_coaching jsonb DEFAULT '[]'::jsonb,
  filters jsonb DEFAULT '{}'::jsonb,
  selected_leads jsonb DEFAULT '[]'::jsonb,
  current_step text DEFAULT 'targeting'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT campaign_drafts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  description text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'completed'::text])),
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  smartlead_campaign_id character varying,
  syndie_campaign_ids ARRAY,
  workflow_json_file text CHECK (workflow_json_file IS NULL OR workflow_json_file ~ '^workflows/[a-zA-Z0-9_-]+\.json$'::text),
  lead_list_id uuid,
  account_id uuid,
  workflow_id text,
  schedule jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.user_accounts(id),
  CONSTRAINT campaigns_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT campaigns_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.company_active_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  job_id text NOT NULL,
  company_name text NOT NULL,
  company_website text,
  linkedin_url text NOT NULL,
  department text NOT NULL,
  job_titles ARRAY,
  match_count integer DEFAULT 0,
  job_data jsonb DEFAULT '{}'::jsonb CHECK (validate_job_data(job_data)),
  linkedin_jobs jsonb DEFAULT '[]'::jsonb,
  career_page_jobs jsonb DEFAULT '[]'::jsonb,
  processing_status text DEFAULT 'pending'::text CHECK (processing_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'timeout'::text])),
  error_message text,
  scraped_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_active_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT company_active_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT company_active_jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.job_filter_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  job_id text NOT NULL UNIQUE,
  original_filename text NOT NULL,
  total_companies integer DEFAULT 0,
  processed_companies integer DEFAULT 0,
  successful_companies integer DEFAULT 0,
  failed_companies integer DEFAULT 0,
  departments ARRAY NOT NULL,
  job_titles ARRAY,
  processing_status text DEFAULT 'pending'::text CHECK (processing_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  csv_output_url text,
  error_message text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_filter_requests_pkey PRIMARY KEY (id),
  CONSTRAINT job_filter_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT job_filter_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.lead_lists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  connected_account_id uuid,
  name text NOT NULL,
  description text,
  total_leads integer DEFAULT 0,
  processed_leads integer DEFAULT 0,
  failed_leads integer DEFAULT 0,
  original_filename text,
  csv_file_url text,
  sample_csv_url text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  processing_started_at timestamp with time zone,
  processing_completed_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  campaign_id uuid,
  icpData json,
  CONSTRAINT lead_lists_pkey PRIMARY KEY (id),
  CONSTRAINT lead_lists_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT lead_lists_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT lead_lists_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT lead_lists_connected_account_id_fkey FOREIGN KEY (connected_account_id) REFERENCES public.user_accounts(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  full_name text NOT NULL,
  first_name text,
  last_name text,
  email text,
  phone text,
  title text,
  headline text,
  seniority text,
  company text,
  industry text,
  location text,
  linkedin_url text,
  twitter_url text,
  status text DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'contacted'::text, 'replied'::text, 'positive'::text, 'neutral'::text, 'negative'::text, 'unsubscribed'::text])),
  source text DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['manual'::text, 'zoominfo'::text, 'apollo'::text, 'clearbit'::text, 'website_visitor'::text, 'syndie'::text])),
  enrichment_data jsonb DEFAULT '{}'::jsonb,
  verified boolean DEFAULT false,
  confidence numeric DEFAULT 0,
  smartlead_campaign_id text,
  last_email_event text,
  last_event_timestamp timestamp with time zone,
  syndie_lead_id text UNIQUE,
  linkedin_connection_status text DEFAULT 'not_connected'::text,
  steps jsonb DEFAULT '[]'::jsonb CHECK (validate_syndie_steps(steps)),
  campaign_info jsonb DEFAULT '{}'::jsonb,
  seat_info jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  clento_campaign_id text,
  syndie_campaign_id text,
  crm_entry smallint DEFAULT '0'::smallint,
  lead_list_id uuid,
  user_id uuid,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT leads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT leads_lead_list_id_fkey FOREIGN KEY (lead_list_id) REFERENCES public.lead_lists(id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  role character varying DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'member'::character varying, 'viewer'::character varying]::text[])),
  permissions jsonb DEFAULT '{}'::jsonb,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'pending'::character varying]::text[])),
  invited_by uuid,
  invited_at timestamp with time zone,
  joined_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT organization_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_org_id text NOT NULL UNIQUE,
  name text NOT NULL,
  slug text UNIQUE,
  logo_url text,
  website_url text,
  industry text,
  company_size character varying,
  plan character varying DEFAULT 'free'::character varying CHECK (plan::text = ANY (ARRAY['free'::character varying, 'starter'::character varying, 'pro'::character varying, 'enterprise'::character varying]::text[])),
  billing_email text,
  subscription_status character varying DEFAULT 'active'::character varying,
  monthly_campaign_limit integer DEFAULT 5,
  monthly_lead_limit integer DEFAULT 1000,
  user_limit integer DEFAULT 5,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  permissible_seats integer NOT NULL DEFAULT 5 CHECK (permissible_seats > 0),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sequence_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid,
  lead_id uuid,
  step_number integer NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['email'::text, 'linkedin_invite'::text, 'linkedin_message'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'scheduled'::text, 'sent'::text, 'failed'::text, 'skipped'::text])),
  send_time timestamp with time zone,
  sent_at timestamp with time zone,
  payload jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sequence_steps_pkey PRIMARY KEY (id),
  CONSTRAINT sequence_steps_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.syndie_access_tokens (
  organization_id text NOT NULL,
  api_token text NOT NULL,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT syndie_access_tokens_pkey PRIMARY KEY (id)
);
CREATE TABLE public.syndie_to_clento_orgs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clento_org_id text NOT NULL,
  syndie_org_id text NOT NULL,
  org_name text
);
CREATE TABLE public.user_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid,
  unipile_account_id text UNIQUE,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['linkedin'::text, 'email'::text, 'twitter'::text, 'facebook'::text, 'instagram'::text, 'whatsapp'::text, 'telegram'::text, 'messenger'::text])),
  account_type text NOT NULL DEFAULT 'personal'::text CHECK (account_type = ANY (ARRAY['personal'::text, 'business'::text, 'page'::text])),
  display_name text NOT NULL,
  username text,
  email text,
  profile_picture_url text,
  connection_status text DEFAULT 'disconnected'::text CHECK (connection_status = ANY (ARRAY['connected'::text, 'disconnected'::text, 'expired'::text, 'error'::text, 'pending'::text, 'credentials'::text])),
  last_sync_at timestamp with time zone,
  expires_at timestamp with time zone,
  unipile_data jsonb DEFAULT '{}'::jsonb,
  capabilities jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT user_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_accounts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_profile (
  user_id uuid NOT NULL,
  company_name text,
  website_url text,
  site_summary text,
  linkedin_connected boolean DEFAULT false,
  completed boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  onboarding_completed boolean DEFAULT false,
  onboarding_step_completed jsonb DEFAULT '{}'::jsonb,
  linkedin_accounts_connected integer DEFAULT 0,
  organization_id uuid,
  CONSTRAINT user_profile_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_profile_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clerk_id text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  full_name text,
  company_name text,
  website_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  isAdmin smallint DEFAULT '0'::smallint,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.website_analysis (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  website_url text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'analyzing'::text, 'completed'::text, 'failed'::text])),
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  core_offer text,
  icp_summary text,
  target_personas jsonb DEFAULT '[]'::jsonb,
  case_studies jsonb DEFAULT '[]'::jsonb,
  lead_magnets jsonb DEFAULT '[]'::jsonb,
  competitive_advantages ARRAY DEFAULT '{}'::text[],
  technology_stack ARRAY DEFAULT '{}'::text[],
  social_proof jsonb DEFAULT '{}'::jsonb,
  pages_analyzed integer DEFAULT 0,
  total_pages_found integer DEFAULT 0,
  analysis_duration_seconds integer,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  analysis_status character varying DEFAULT 'pending'::character varying CHECK (analysis_status::text = ANY (ARRAY['pending'::character varying, 'analyzing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  industry character varying,
  business_model character varying,
  target_market_summary text,
  tech_stack jsonb DEFAULT '[]'::jsonb,
  pages_discovered jsonb DEFAULT '[]'::jsonb,
  ai_model_used character varying,
  confidence_score numeric,
  started_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  CONSTRAINT website_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT website_analysis_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT website_analysis_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);